// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZjPDNwLL9OgbBTEbgW5h4LqdOvaHF9g4',
    appId: '1:58632345191:web:b45c292c7d01282aca66c2',
    messagingSenderId: '58632345191',
    projectId: 'mediplanner-2f682',
    authDomain: 'mediplanner-2f682.firebaseapp.com',
    storageBucket: 'mediplanner-2f682.appspot.com',
    measurementId: 'G-NWYDQT54YL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlVn4cuH9vYT-uS0ZHRrFy8W1CHmojhag',
    appId: '1:58632345191:android:8a69d2589bda9e2eca66c2',
    messagingSenderId: '58632345191',
    projectId: 'mediplanner-2f682',
    storageBucket: 'mediplanner-2f682.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNUbJLoUg16v-nRCtw5nvvIt8rv6kuRq0',
    appId: '1:58632345191:ios:d47b8dc6d3ab9cfdca66c2',
    messagingSenderId: '58632345191',
    projectId: 'mediplanner-2f682',
    storageBucket: 'mediplanner-2f682.appspot.com',
    iosClientId:
        '58632345191-mq483qu42ibeol1fn3bctr6i5ueia96a.apps.googleusercontent.com',
    iosBundleId: 'com.example.mediplanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNUbJLoUg16v-nRCtw5nvvIt8rv6kuRq0',
    appId: '1:58632345191:ios:d47b8dc6d3ab9cfdca66c2',
    messagingSenderId: '58632345191',
    projectId: 'mediplanner-2f682',
    storageBucket: 'mediplanner-2f682.appspot.com',
    iosClientId:
        '58632345191-mq483qu42ibeol1fn3bctr6i5ueia96a.apps.googleusercontent.com',
    iosBundleId: 'com.example.mediplanner',
  );
}
